const env = import.meta.env;

export const ENV = {
  API_BASE_URL: env.VITE_API_BASE_URL,
  TENANT_DOMAIN: env.VITE_TENANT_DOMAIN,
  TENANT_ID: env.VITE_TENANT_ID,
  FRONTEND_CLIENT_ID: env.VITE_FRONTEND_CLIENT_ID,
  API_CLIENT_ID: env.VITE_API_CLIENT_ID,
  AUTHORITY: env.VITE_AUTHORITY,
  REDIRECT_URI: env.VITE_REDIRECT_URI,
  POST_LOGOUT_REDIRECT_URI: env.VITE_POST_LOGOUT_REDIRECT_URI,
  SCOPE: env.VITE_SCOPE,
};