import { CompanyForm } from "./types/companyForm.types";
export const emptyCompanyForm: CompanyForm = {
  nombre: "",
  pais: "",
  sedes: "",
  tamaño: "",
  sector: "",
  img: null,
  activo: false,
  colorPrimario: "",
  colorSecundario: "",
  colorTerciario: "",
  HeaderColorTextos: "",
  HeaderColorIcons: "",
  navColorIcon: "",
  navColorFondoIcon: "",
  btnPrimarioColor: "",
  btnPrimarioColorTexto: "",
  btnSecundarioColor: "",
  btnSecundarioColorTexto: "",
};
